### ISSUE TITLE
Support for ECMA6

### ISSUE THREAD

**Issue by ghost** [iocast/atom-esdoc#1]
doesnt have support for multiple ecma6 features like:

const;
let;
methods inside class (without "function" declaration);
async methods;
constructor
etc...

**Comment by iocast** [comment]
could you please let me know what is exactly not working and what you expect

constructor should work
```javascript
export class test{

  /**
   *
   *
   * @param {type}	hello - this is the parameter hello
   */
  constructor(hello) {
    this.name = hello;
  }

  /**
   *
   *
   * @param {type}	a - this is the parameter a
   * @param {type}	b - this is the parameter b
   * @param {type}	c - this is the parameter c
   *
   * @return String
   */
  calculate(a, b, c) {
    return "";
  }
...
```

for `async` the return type `Promise` is not automatically set.

`const` and `let` does not work
